config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from wagtail import urls as wagtail_urls
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.documents import urls as wagtaildocs_urls

from lemarche.utils.admin.admin_site import admin_site


urlpatterns = [
    path("admin/", admin_site.urls),
    path("api/", include("lemarche.api.urls")),
    path("accounts/", include("lemarche.www.auth.urls")),
    path("besoins/", include("lemarche.www.tenders.urls")),
    path("prestataires/", include("lemarche.www.siaes.urls")),
    path("profil/", include("lemarche.www.dashboard.urls")),
    path("profil/prestataires/", include("lemarche.www.dashboard_siaes.urls")),
    path("profil/reseaux/", include("lemarche.www.dashboard_networks.urls")),
    path("profil/listes-dachats/", include("lemarche.www.dashboard_favorites.urls")),
    path("select2/", include("django_select2.urls")),
    # admin blog
    path("cms/", include(wagtailadmin_urls)),
    # url docuemnts of glog
    path("documents/", include(wagtaildocs_urls)),
    # urls pages blog
    path("", include("lemarche.www.pages.urls")),
    path("", include(wagtail_urls)),
]

if settings.DEBUG and "debug_toolbar" in settings.INSTALLED_APPS:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

if settings.BITOUBI_ENV in (
    "dev",
    "review_app",
):
    urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + urlpatterns

itou_c4_api/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [path("admin/", admin.site.urls), path("", include("itou_c4_api.c4_directory.urls"))] + static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
)

lemarche/api/urls.py
from django.urls import path
from django.views.generic import RedirectView, TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
from rest_framework import routers

from lemarche.api.emails.views import InboundParsingEmailView
from lemarche.api.networks.views import NetworkViewSet
from lemarche.api.perimeters.views import PerimeterAutocompleteViewSet, PerimeterKindViewSet, PerimeterViewSet
from lemarche.api.sectors.views import SectorViewSet
from lemarche.api.siaes.views import SiaeKindViewSet, SiaePrestaTypeViewSet, SiaeViewSet
from lemarche.api.tenders.views import TenderAmountViewSet, TenderKindViewSet, TenderViewSet


# https://docs.djangoproject.com/en/dev/topics/http/urls/#url-namespaces-and-included-urlconfs
app_name = "api"

router = routers.DefaultRouter()
router.register(r"siae/kinds", SiaeKindViewSet, basename="siae-kinds")
router.register(r"siae/presta-types", SiaePrestaTypeViewSet, basename="siae-presta-types")
router.register(r"siae", SiaeViewSet, basename="siae")
router.register(r"sectors", SectorViewSet, basename="sectors")
router.register(r"networks", NetworkViewSet, basename="networks")
router.register(r"perimeters/kinds", PerimeterKindViewSet, basename="perimeter-kinds")
router.register(r"perimeters/autocomplete", PerimeterAutocompleteViewSet, basename="perimeters-autocomplete")
router.register(r"perimeters", PerimeterViewSet, basename="perimeters")
router.register(r"tenders/kinds", TenderKindViewSet, basename="tender-kinds")
router.register(r"tenders/amounts", TenderAmountViewSet, basename="tender-amounts")
router.register(r"tenders", TenderViewSet, basename="tenders")

urlpatterns = [
    path("", TemplateView.as_view(template_name="api/home.html"), name="home"),
    # Additional API endpoints
    path("siae/slug/<str:slug>/", SiaeViewSet.as_view({"get": "retrieve_by_slug"}), name="siae-retrieve-by-slug"),
    path("siae/siret/<str:siret>/", SiaeViewSet.as_view({"get": "retrieve_by_siret"}), name="siae-retrieve-by-siret"),
    path(
        "siaes/siret/<str:siret>/",
        RedirectView.as_view(pattern_name="api:siae-retrieve-by-siret", permanent=True),
        name="old_api_siae_siret",
    ),
    path("inbound-email-parsing/", InboundParsingEmailView.as_view(), name="inbound-email-parsing"),
    # Swagger / OpenAPI documentation
    path("schema/", SpectacularAPIView.as_view(), name="schema"),
    path("docs/", SpectacularSwaggerView.as_view(url_name="api:schema"), name="swagger-ui"),
    path("redoc/", SpectacularRedocView.as_view(url_name="api:schema"), name="redoc"),
]

urlpatterns += router.urls

lemarche/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [path("admin/", admin.site.urls), path("", include("lemarche.api.urls"))] + static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
)

lemarche/www/dashboard/urls.py
from django.urls import path

from lemarche.www.dashboard.views import DashboardHomeView, ProfileEditView


app_name = "dashboard"

urlpatterns = [
    path("", DashboardHomeView.as_view(), name="home"),
    path("modifier/", ProfileEditView.as_view(), name="profile_edit"),
    # FavoriteList
    # see dashboard_favorites/urls.py
    # Network
    # see dashboard_networks/urls.py
    # Adopt Siae, Edit Siae & Siae Users
    # see dashboard_siaes/urls.py
]

lemarche/www/pages/urls.py
from django.urls import path
from django.views.generic import TemplateView

from lemarche.www.pages.views import (
    CompanyReferenceCalculatorView,
    ContactView,
    HomeView,
    ImpactCalculatorView,
    PageView,
    SiaeGroupListView,
    SocialImpactBuyersCalculatorView,
    StatsView,
    TrackView,
    trigger_error,
)


# https://docs.djangoproject.com/en/dev/topics/http/urls/#url-namespaces-and-included-urlconfs
app_name = "pages"

urlpatterns = [
    path("ancien_accueil", HomeView.as_view(), name="home"),
    path("contact/", ContactView.as_view(), name="contact"),
    # Calculator endpoints
    path("calibrer-achat-socialement-responsable/", ImpactCalculatorView.as_view(), name="impact_calculator"),
    path(
        "calculer-impact-social-achat-inclusif/",
        SocialImpactBuyersCalculatorView.as_view(),
        name="buyer_social_impact_calculator",
    ),
    path("acheteurs-reference-client/", CompanyReferenceCalculatorView.as_view(), name="company_reference_calculator"),
    # Other dynamic pages
    path("groupements/", SiaeGroupListView.as_view(), name="groupements"),
    path("stats/", StatsView.as_view(), name="stats"),
    # Static pages
    path(
        "filiere/restauration/",
        TemplateView.as_view(template_name="pages/filiere_restauration.html"),
        name="filiere_restauration",
    ),
    path(
        "filiere/recyclage/",
        TemplateView.as_view(template_name="pages/filiere_recyclage.html"),
        name="filiere_recyclage",
    ),
    path(
        "decouvrir-inclusion/",
        TemplateView.as_view(template_name="pages/decouvrir-inclusion.html"),
        name="decouvrir_inclusion",
    ),
    path(
        "partenaires/",
        TemplateView.as_view(template_name="pages/partenaires.html"),
        name="partenaires",
    ),
    path(
        "valoriser-achats/",
        TemplateView.as_view(template_name="pages/valoriser-achats.html"),
        name="valoriser_achats",
    ),
    path(
        "accessibilite/",
        TemplateView.as_view(template_name="pages/accessibilite.html"),
        name="accessibilite",
    ),
    # Sentry endpoint for frontend errors
    path("sentry-debug/", trigger_error, name="sentry_debug"),
    # Tracking endpoint for the frontend
    path("track/", TrackView.as_view(), name="track_frontend"),
    # Flatpages (created in the admin: faq, qui-sommes-nous, cgu, confidentialité)
    # TODO: move to wagtail?
    # path("", include("django.contrib.flatpages.urls")),
    # path("<path:url>", PageView.as_view(), name="flatpage"),  # conflict with wagtail_urls
    path("qui-sommes-nous/", PageView.as_view(), {"url": "/qui-sommes-nous/"}, name="qui-sommes-nous"),
    path("faq/", PageView.as_view(), {"url": "/faq/"}, name="faq"),
    path(
        "2021-10-06-le-marche-fait-peau-neuve/",
        PageView.as_view(),
        {"url": "/2021-10-06-le-marche-fait-peau-neuve/"},
        name="2021-10-06-le-marche-fait-peau-neuve",
    ),
    path("mentions-legales/", PageView.as_view(), {"url": "/mentions-legales/"}, name="mentions-legales"),
    path("cgu/", PageView.as_view(), {"url": "/cgu/"}, name="cgu"),
    path("cgu-api/", PageView.as_view(), {"url": "/cgu-api/"}, name="cgu-api"),
    path("confidentialite/", PageView.as_view(), {"url": "/confidentialite/"}, name="confidentialite"),
    # Error pages
    path("403/", TemplateView.as_view(template_name="403.html"), name="403"),
    path("404/", TemplateView.as_view(template_name="404.html"), name="404"),
    path("500/", TemplateView.as_view(template_name="500.html"), name="500"),
]

lemarche/www/siae/urls.py
from django.urls import path

from lemarche.www.siae.views import SiaeDetailView, SiaeSearchResultsDownloadView, SiaeSearchResultsView


# https://docs.djangoproject.com/en/dev/topics/http/urls/#url-namespaces-and-included-urlconfs
app_name = "siae"

urlpatterns = [
    path("", SiaeSearchResultsView.as_view(), name="search_results"),
    path("download/", SiaeSearchResultsDownloadView.as_view(), name="search_results_download"),
    path("<str:slug>/", SiaeDetailView.as_view(), name="detail"),
]

lemarche/companies/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.utils import timezone
from django_better_admin_arrayfield.models.fields import ArrayField


class CompanyQuerySet(models.QuerySet):
    def has_user(self):
        return self.filter(users__isnull=False).distinct()

    def has_email_domain(self):
        return self.exclude(email_domain_list=[])


class Company(models.Model):
    name = models.CharField(verbose_name="Nom", max_length=255)
    slug = models.SlugField(verbose_name="Slug", max_length=255, unique=True)
    description = models.TextField(verbose_name="Description", blank=True)
    siret = models.CharField(verbose_name="Siret", max_length=14, blank=True)
    website = models.URLField(verbose_name="Site web", blank=True)
    logo_url = models.URLField(verbose_name="Lien vers le logo", max_length=500, blank=True)

    email_domain_list = ArrayField(
        verbose_name="Liste des noms de domaine d'e-mails",
        help_text="@entreprise.fr (sans le @)",
        base_field=models.CharField(max_length=255),
        blank=True,
        default=list,
    )

    created_at = models.DateTimeField(verbose_name="Date de création", default=timezone.now)
    updated_at = models.DateTimeField(verbose_name="Date de modification", auto_now=True)

    objects = models.Manager.from_queryset(CompanyQuerySet)()

    class Meta:
        verbose_name = "Entreprise"
        verbose_name_plural = "Entreprises"

    def __str__(self):
        return self.name

    def set_slug(self):
        """
        The slug field should be unique.
        """
        if not self.slug:
            self.slug = slugify(self.name)[:50]

    def save(self, *args, **kwargs):
        """Generate the slug field before saving."""
        self.set_slug()
        super().save(*args, **kwargs)

lemarche/conversations/models.py
from uuid import uuid4

from django.conf import settings
from django.db import IntegrityError, models
from django.db.models import Func, IntegerField, Q
from django.utils import timezone
from django.utils.text import slugify
from django_extensions.db.fields import ShortUUIDField
from shortuuid import uuid


class ConversationQuerySet(models.QuerySet):
    def has_answer(self):
        return self.exclude(data=[])

    def with_answer_count(self):
        return self.annotate(answer_count=Func("data", function="jsonb_array_length", output_field=IntegerField()))

    def get_conv_from_uuid(self, conv_uuid: str, version=1):
        """get conv form
        Args:
            conv_uuid (str): _description_

        Returns:
            [VERSION, UUID, KIND_SENDER]
        """
        if version == 0:
            return self.get(uuid=conv_uuid)
        else:
            return self.get(Q(sender_encoded__endswith=conv_uuid) | Q(siae_encoded__endswith=conv_uuid))


class Conversation(models.Model):
    KIND_SEARCH = "SEARCH"
    KIND_TENDER = "TENDER"
    KIND_CHOICES = (
        (KIND_SEARCH, "Recherche"),
        (KIND_TENDER, "Dépôt de besoin"),
    )

    USER_KIND_SENDER_TO_BUYER = "b"
    USER_KIND_SENDER_TO_SIAE = "s"

    uuid = ShortUUIDField(
        verbose_name="Identifiant UUID",
        default=uuid,
        editable=False,
        unique=True,
        db_index=True,
        auto_created=True,
    )

    sender_encoded = models.CharField(
        verbose_name="Identifiant initiateur", unique=True, db_index=True, max_length=255
    )
    siae_encoded = models.CharField(verbose_name="Identifiant structure", unique=True, db_index=True, max_length=255)
    version = models.PositiveIntegerField(verbose_name="Version", default=1)

    kind = models.CharField(
        verbose_name="Type de conversation", default=KIND_SEARCH, choices=KIND_CHOICES, max_length=10, db_index=True
    )
    sender_user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name="Utilisateur à l'initiative",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )
    sender_email = models.EmailField(verbose_name="Email de l'initiateur de la conversation", null=True)
    sender_first_name = models.CharField(verbose_name="Prénom", max_length=150)
    sender_last_name = models.CharField(verbose_name="Nom", max_length=150)

    title = models.CharField(verbose_name="Objet de la première demande", max_length=200)
    initial_body_message = models.TextField(verbose_name="Message initial", blank=True)
    siae = models.ForeignKey(
        "siaes.Siae", verbose_name="Structure", on_delete=models.CASCADE, null=True, related_name="conversations"
    )

    data = models.JSONField(default=list)

    created_at = models.DateTimeField(verbose_name="Date de création", default=timezone.now)
    updated_at = models.DateTimeField(verbose_name="Date de modification", auto_now=True)
    validated_at = models.DateTimeField(verbose_name="Date de validation", blank=True, null=True)

    objects = models.Manager.from_queryset(ConversationQuerySet)()

    class Meta:
        verbose_name = "Conversation"

    def __str__(self):
        return self.title

    def set_sender_encoded(self):
        """
        The UUID of sender.
        """
        if not self.sender_encoded:
            slug_sender_full_name = slugify(self.sender_full_name).replace("-", "_")
            self.sender_encoded = f"{slug_sender_full_name}_{str(uuid4())[:4]}"

    def set_siae_encoded(self):
        """
        The UUID of siae.
        """
        if not self.siae_encoded:
            if self.siae.contact_full_name:
                siae_slug_full_name = slugify(self.siae.contact_full_name).replace("-", "_")
            else:
                siae_slug_full_name = self.siae.slug.replace("-", "_")
            self.siae_encoded = f"{siae_slug_full_name}_{str(uuid4())[:4]}"

    def save(self, *args, **kwargs):
        """
        - generate the uuid field
        """
        try:
            self.set_sender_encoded()
            self.set_siae_encoded()
            super().save(*args, **kwargs)
        except IntegrityError as e:
            # check that it's a new UUID conflict
            # Full message expected: duplicate key value violates unique constraint "conversations_conversation_sender_encoded_0f0b821f_uniq" DETAIL:  Key (sender_encoded)=(...) already exists.  # noqa
            if "conversations_conversation_sender_encoded" in str(e):
                self.set_sender_encoded()
                super().save(*args, **kwargs)
            if "conversations_conversation_siae_encoded" in str(e):
                self.set_siae_encoded()
                super().save(*args, **kwargs)
            else:
                raise e

    def get_user_kind(self, conv_uuid):
        # method only available in version >= 1
        if self.sender_encoded.endswith(conv_uuid):
            return self.USER_KIND_SENDER_TO_BUYER
        elif self.siae_encoded.endswith(conv_uuid):
            return self.USER_KIND_SENDER_TO_SIAE

    @property
    def sender_email_buyer(self):
        return self.sender_email

    @property
    def sender_full_name(self):
        return f"{self.sender_first_name} {self.sender_last_name}"

    @property
    def sender_email_buyer_encoded(self):
        if self.version == 0:
            # for legacy
            return f"{self.uuid}_{self.USER_KIND_SENDER_TO_BUYER}@{settings.INBOUND_PARSING_DOMAIN_EMAIL}"
        if self.version == 1:
            return f"{self.sender_encoded}@{settings.INBOUND_PARSING_DOMAIN_EMAIL}"

    @property
    def sender_email_siae_encoded(self):
        if self.version == 0:
            # for legacy
            return f"{self.uuid}_{self.USER_KIND_SENDER_TO_SIAE}@{settings.INBOUND_PARSING_DOMAIN_EMAIL}"
        if self.version == 1:
            return f"{self.siae_encoded}@{settings.INBOUND_PARSING_DOMAIN_EMAIL}"

    @property
    def sender_email_siae(self):
        return self.siae.contact_email

    @property
    def nb_messages(self):
        """Number of messages is the len of data item + the initial message

        Returns:
            int: Number of all messages
        """
        return len(self.data) + 1

    @property
    def is_validated(self) -> bool:
        return self.validated_at is not None

    def set_validated(self):
        self.validated_at = timezone.now()
        self.save()

lemarche/templates/dashboard/profile_favorite_list.html
{% extends "layouts/base.html" %}
{% load bootstrap4 %}

{% block title %}Liste d'achat favoris{{ block.super }}{% endblock %}

{% block breadcrumbs %}
<section>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav class="c-breadcrumb c-breadcrumb--marche" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'wagtail_serve' '' %}">Accueil</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'dashboard:home' %}">Tableau de bord</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Liste d'achat favoris</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block content %}
<section class="pt-4 pb-6">
    <div class="container">
        <div class="row">
            <div class="col-12 col-lg-8">
                <h1 class="h1 mb-3 mb-lg-5">
                    <strong>Liste d'achat favoris</strong>
                </h1>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-lg-8">
                <!-- New list -->
                <h2>Nouvelle liste</h2>
                <form method="POST" action="{% url 'dashboard:profile_favorite_list_create' %}">
                    {% csrf_token %}
                    {% bootstrap_form_errors form type="all" %}
                    <label class="mb-2 d-inline-block font-weight-bold" for="id_name">Créer une {% if favorite_lists.count %}nouvelle {% endif %}liste</label>
                    <div class="form-row">
                        <div class="form-group col">
                            {% bootstrap_field form.name show_label=False %}
                        </div>
                        <div class="form-group col-auto">
                            <button class="btn btn-primary btn-ico" type="submit" name="action" value="create">
                                <span>Créer</span>
                                <i class="ri-add-fill ri-lg"></i>
                            </button>
                        </div>
                    </div>
                </form>

                <!-- Existing list(s) -->
                {% if favorite_lists.count %}
                    <h2>{{ favorite_lists.count }} liste{% if favorite_lists.count > 1 %}s{% endif %} existante{% if favorite_lists.count > 1 %}s{% endif %}</h2>
                    <ul class="list-group">
                    {% for favorite_list in favorite_lists.all %}
                        <li class="list-group-item">
                            <a href="{% url 'dashboard:profile_favorite_list_detail' favorite_list.slug %}" class="d-flex justify-content-between align-items-center text-decoration-none" title="Voir la liste">
                                <span>{{ favorite_list.name }} <span class="ml-2 fs-xs badge badge-marche-light badge-pill">{{ favorite_list.siaes.count }}</span></span>
                                <i class="ri-eye-line ri-lg"></i>
                            </a>
                        </li>
                    {% endfor %}
                    </ul>
                {% else %}
                    <p class="text-danger font-weight-bold">Vous n'avez pas encore créé de listes !</p>
                {% endif %}
            </div>
        </div>

    </div>
</section>
{% endblock %}

lemarche/templates/dashboard/siae_adopt_confirm.html
{% extends "layouts/base.html" %}
{% load static get_verbose_name %}

{% block title %}Vérifier ma structure{{ block.super }}{% endblock %}

{% block breadcrumbs %}
<section>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav class="c-breadcrumb c-breadcrumb--marche" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'pages:home' %}">Accueil</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'dashboard:home' %}">Mon espace</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'dashboard:siae_search_by_siret' %}">Rechercher ma structure</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Vérifier ma structure</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block content %}
<section class="pt-4 pt-lg-6 pb-6 pb-lg-8">
    <div class="container container-max-lg">
        <div class="row">
            <div class="col-12">
                <h2 class="mb-3 mb-lg-5">Dernière vérification</h2>

                <p>
                    Vérifiez si ces données correspondent bien à votre structure.<br />
                    <small>Données fixes provenant de l'ASP.</small>
                </p>

                
                <p title="{% get_verbose_name siae 'name' %}">
                    <strong>{% get_verbose_name siae 'name' %} :</strong>
                    {{ siae.name }}
                </p>
                <p title="{% get_verbose_name siae 'brand' %}">
                    <strong>{% get_verbose_name siae 'brand' %} :</strong>
                    {{ siae.brand }}
                </p>
                <p title="{% get_verbose_name siae 'siret' %}">
                    <strong>{% get_verbose_name siae 'siret' %} :</strong>
                    {{ siae.siret }}
                </p>
                <p title="{% get_verbose_name siae 'kind' %}">
                    <strong>{% get_verbose_name siae 'kind' %} :</strong>
                    {{ siae.get_kind_display }}
                </p>
                <p title="{% get_verbose_name siae 'nature' %}">
                    <strong>{% get_verbose_name siae 'nature' %} :</strong>
                    {{ siae.get_nature_display }}
                </p>
                <p title="{% get_verbose_name siae 'city' %}">
                    <strong>{% get_verbose_name siae 'city' %} :</strong>
                    {{ siae.city }}
                </p>
                <p title="{% get_verbose_name siae 'post_code' %}">
                    <strong>{% get_verbose_name siae 'post_code' %} :</strong>
                    {{ siae.post_code }}
                </p>
                <p title="{% get_verbose_name siae 'region' %}">
                    <strong>{% get_verbose_name siae 'region' %} :</strong>
                    {{ siae.region }}
                </p>

                <form method="POST" class="mb-3 mb-lg-5">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-12 col-md-auto pt-3">
                            <a href="{% url 'dashboard:siae_search_by_siret' %}" class="btn btn-outline-primary btn-block reset btn-ico">
                                Non, refaire une recherche <i class="icon-cw"></i>
                            </a>
                        </div>
                        <div class="col-12 col-md-auto pt-3">
                            <button type="submit" class="btn btn-primary btn-block">
                                <span>Je confirme</span>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

lemarche/templates/dashboard/siae_search_by_siret.html
{% extends "layouts/base.html" %}
{% load bootstrap4 get_verbose_name %}

{% block title %}Rechercher ma structure{{ block.super }}{% endblock %}

{% block breadcrumbs %}
<section>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav class="c-breadcrumb c-breadcrumb--marche" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'wagtail_serve' '' %}">Accueil</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'dashboard:home' %}">Tableau de bord</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Rechercher ma structure</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block content %}
<section class="s-section">
    <div class="s-section__container container">
        <div class="row">
            <div class="col-12 col-lg-8">
                <h1><strong>Ma structure</strong></h1>
                <p class="lead mb-0">Recherchez la structure à laquelle vous êtes attaché.</p>
                <p class="mb-3 mb-lg-5">Si vous en avez plusieurs, vous aurez la possibilité de spécifier d'autres structures par la suite.</p>

                <form method="GET" action="{% url 'dashboard_siaes:siae_search_by_siret' %}">
                    {% bootstrap_form_errors form type="all" %}
                    <label class="mb-2 d-inline-block font-weight-bold required" for="id_siret">Entrez le numéro SIRET ou SIREN de votre structure</label>
                    <div class="form-row">
                        <div class="form-group form-group-required col">
                            {% bootstrap_field form.siret show_label=False %}
                        </div>
                        <div class="form-group col-auto">
                            <button class="btn btn-primary btn-ico" type="submit">
                                <span>Rechercher</span>
                                <i class="ri-search-line ri-lg"></i>
                            </button>
                        </div>
                    </div>
                </form>

                {% if siaes %}
                    <h2>{{ siaes.count }} structure{% if siaes.count > 1 %}s{% endif %} trouvée{% if siaes.count > 1 %}s{% endif %}</h2>
                    {% for siae in siaes %}
                        <hr />
                        <div class="row">
                            <div class="col">
                                <p title="{% get_verbose_name siae 'name' %}" class="mb-0">
                                    <strong>{% get_verbose_name siae 'name' %} :</strong>
                                    {{ siae.name }}
                                </p>
                                <p title="{% get_verbose_name siae 'brand' %}" class="mb-0">
                                    <strong>{% get_verbose_name siae 'brand' %} :</strong>
                                    {{ siae.brand|default:'' }}
                                </p>
                                <p title="{% get_verbose_name siae 'siret' %}" class="mb-0">
                                    <strong>{% get_verbose_name siae 'siret' %} :</strong>
                                    {{ siae.siret_display }}
                                </p>
                                <p title="Localisation" class="mb-0">
                                    <strong>Localisation :</strong>
                                    {{ siae.city }} {{ siae.post_code }}
                                </p>
                            </div>
                            <div class="col text-right">
                                <br />
                                <a href="{% url 'dashboard_siaes:siae_search_adopt_confirm' siae.slug %}" class="btn btn-outline-primary">
                                    <span>Sélectionner</span>
                                </a>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
                {% if not siaes and form.is_valid %}
                    <div class="alert alert-danger mb-3 mb-lg-5" role="status">
                        Nous n'avons pas retrouvé votre numéro de Siret. Merci de vérifier votre numéro.<br />
                        Dans le cas où le problème persiste, contactez <a href="{% url 'pages:contact' %}">notre support</a>.
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</section>
{% endblock %}