config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from wagtail import urls as wagtail_urls
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.documents import urls as wagtaildocs_urls

from lemarche.utils.admin.admin_site import admin_site


urlpatterns = [
    path("admin/", admin_site.urls),
    path("api/", include("lemarche.api.urls")),
    path("accounts/", include("lemarche.www.auth.urls")),
    path("besoins/", include("lemarche.www.tenders.urls")),
    path("prestataires/", include("lemarche.www.siaes.urls")),
    path("profil/", include("lemarche.www.dashboard.urls")),
    path("profil/prestataires/", include("lemarche.www.dashboard_siaes.urls")),
    path("profil/reseaux/", include("lemarche.www.dashboard_networks.urls")),
    path("profil/listes-dachats/", include("lemarche.www.dashboard_favorites.urls")),
    path("select2/", include("django_select2.urls")),
    # admin blog
    path("cms/", include(wagtailadmin_urls)),
    # url docuemnts of glog
    path("documents/", include(wagtaildocs_urls)),
    # urls pages blog
    path("", include("lemarche.www.pages.urls")),
    path("", include(wagtail_urls)),
]

if settings.DEBUG and "debug_toolbar" in settings.INSTALLED_APPS:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

if settings.BITOUBI_ENV in (
    "dev",
    "review_app",
):
    urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + urlpatterns

itou_c4_api/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [path("admin/", admin.site.urls), path("", include("itou_c4_api.c4_directory.urls"))] + static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
)

lemarche/api/urls.py
from django.urls import path
from django.views.generic import RedirectView, TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
from rest_framework import routers

from lemarche.api.emails.views import InboundParsingEmailView
from lemarche.api.networks.views import NetworkViewSet
from lemarche.api.perimeters.views import PerimeterAutocompleteViewSet, PerimeterKindViewSet, PerimeterViewSet
from lemarche.api.sectors.views import SectorViewSet
from lemarche.api.siaes.views import SiaeKindViewSet, SiaePrestaTypeViewSet, SiaeViewSet
from lemarche.api.tenders.views import TenderAmountViewSet, TenderKindViewSet, TenderViewSet


# https://docs.djangoproject.com/en/dev/topics/http/urls/#url-namespaces-and-included-urlconfs
app_name = "api"

router = routers.DefaultRouter()
router.register(r"siae/kinds", SiaeKindViewSet, basename="siae-kinds")
router.register(r"siae/presta-types", SiaePrestaTypeViewSet, basename="siae-presta-types")
router.register(r"siae", SiaeViewSet, basename="siae")
router.register(r"sectors", SectorViewSet, basename="sectors")
router.register(r"networks", NetworkViewSet, basename="networks")
router.register(r"perimeters/kinds", PerimeterKindViewSet, basename="perimeter-kinds")
router.register(r"perimeters/autocomplete", PerimeterAutocompleteViewSet, basename="perimeters-autocomplete")
router.register(r"perimeters", PerimeterViewSet, basename="perimeters")
router.register(r"tenders/kinds", TenderKindViewSet, basename="tender-kinds")
router.register(r"tenders/amounts", TenderAmountViewSet, basename="tender-amounts")
router.register(r"tenders", TenderViewSet, basename="tenders")

urlpatterns = [
    path("", TemplateView.as_view(template_name="api/home.html"), name="home"),
    # Additional API endpoints
    path("siae/slug/<str:slug>/", SiaeViewSet.as_view({"get": "retrieve_by_slug"}), name="siae-retrieve-by-slug"),
    path("siae/siret/<str:siret>/", SiaeViewSet.as_view({"get": "retrieve_by_siret"}), name="siae-retrieve-by-siret"),
    path(
        "siaes/siret/<str:siret>/",
        RedirectView.as_view(pattern_name="api:siae-retrieve-by-siret", permanent=True),
        name="old_api_siae_siret",
    ),
    path("inbound-email-parsing/", InboundParsingEmailView.as_view(), name="inbound-email-parsing"),
    # Swagger / OpenAPI documentation
    path("schema/", SpectacularAPIView.as_view(), name="schema"),
    path("docs/", SpectacularSwaggerView.as_view(url_name="api:schema"), name="swagger-ui"),
    path("redoc/", SpectacularRedocView.as_view(url_name="api:schema"), name="redoc"),
]

urlpatterns += router.urls

lemarche/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [path("admin/", admin.site.urls), path("", include("lemarche.api.urls"))] + static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
)

lemarche/www/pages/urls.py
from django.urls import path
from django.views.generic import TemplateView

from lemarche.www.pages.views import (
    CompanyReferenceCalculatorView,
    ContactView,
    HomeView,
    ImpactCalculatorView,
    PageView,
    SiaeGroupListView,
    SocialImpactBuyersCalculatorView,
    StatsView,
    TrackView,
    trigger_error,
)


# https://docs.djangoproject.com/en/dev/topics/http/urls/#url-namespaces-and-included-urlconfs
app_name = "pages"

urlpatterns = [
    path("ancien_accueil", HomeView.as_view(), name="home"),
    path("contact/", ContactView.as_view(), name="contact"),
    # Calculator endpoints
    path("calibrer-achat-socialement-responsable/", ImpactCalculatorView.as_view(), name="impact_calculator"),
    path(
        "calculer-impact-social-achat-inclusif/",
        SocialImpactBuyersCalculatorView.as_view(),
        name="buyer_social_impact_calculator",
    ),
    path("acheteurs-reference-client/", CompanyReferenceCalculatorView.as_view(), name="company_reference_calculator"),
    # Other dynamic pages
    path("groupements/", SiaeGroupListView.as_view(), name="groupements"),
    path("stats/", StatsView.as_view(), name="stats"),
    # Static pages
    path(
        "filiere/restauration/",
        TemplateView.as_view(template_name="pages/filiere_restauration.html"),
        name="filiere_restauration",
    ),
    path(
        "filiere/recyclage/",
        TemplateView.as_view(template_name="pages/filiere_recyclage.html"),
        name="filiere_recyclage",
    ),
    path(
        "decouvrir-inclusion/",
        TemplateView.as_view(template_name="pages/decouvrir-inclusion.html"),
        name="decouvrir_inclusion",
    ),
    path(
        "partenaires/",
        TemplateView.as_view(template_name="pages/partenaires.html"),
        name="partenaires",
    ),
    path(
        "valoriser-achats/",
        TemplateView.as_view(template_name="pages/valoriser-achats.html"),
        name="valoriser_achats",
    ),
    path(
        "accessibilite/",
        TemplateView.as_view(template_name="pages/accessibilite.html"),
        name="accessibilite",
    ),
    # Sentry endpoint for frontend errors
    path("sentry-debug/", trigger_error, name="sentry_debug"),
    # Tracking endpoint for the frontend
    path("track/", TrackView.as_view(), name="track_frontend"),
    # Flatpages (created in the admin: faq, qui-sommes-nous, cgu, confidentialité)
    # TODO: move to wagtail?
    # path("", include("django.contrib.flatpages.urls")),
    # path("<path:url>", PageView.as_view(), name="flatpage"),  # conflict with wagtail_urls
    path("qui-sommes-nous/", PageView.as_view(), {"url": "/qui-sommes-nous/"}, name="qui-sommes-nous"),
    path("faq/", PageView.as_view(), {"url": "/faq/"}, name="faq"),
    path(
        "2021-10-06-le-marche-fait-peau-neuve/",
        PageView.as_view(),
        {"url": "/2021-10-06-le-marche-fait-peau-neuve/"},
        name="2021-10-06-le-marche-fait-peau-neuve",
    ),
    path("mentions-legales/", PageView.as_view(), {"url": "/mentions-legales/"}, name="mentions-legales"),
    path("cgu/", PageView.as_view(), {"url": "/cgu/"}, name="cgu"),
    path("cgu-api/", PageView.as_view(), {"url": "/cgu-api/"}, name="cgu-api"),
    path("confidentialite/", PageView.as_view(), {"url": "/confidentialite/"}, name="confidentialite"),
    # Error pages
    path("403/", TemplateView.as_view(template_name="403.html"), name="403"),
    path("404/", TemplateView.as_view(template_name="404.html"), name="404"),
    path("500/", TemplateView.as_view(template_name="500.html"), name="500"),
]

lemarche/companies/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.utils import timezone
from django_better_admin_arrayfield.models.fields import ArrayField


class CompanyQuerySet(models.QuerySet):
    def has_user(self):
        return self.filter(users__isnull=False).distinct()

    def has_email_domain(self):
        return self.exclude(email_domain_list=[])


class Company(models.Model):
    name = models.CharField(verbose_name="Nom", max_length=255)
    slug = models.SlugField(verbose_name="Slug", max_length=255, unique=True)
    description = models.TextField(verbose_name="Description", blank=True)
    siret = models.CharField(verbose_name="Siret", max_length=14, blank=True)
    website = models.URLField(verbose_name="Site web", blank=True)
    logo_url = models.URLField(verbose_name="Lien vers le logo", max_length=500, blank=True)

    email_domain_list = ArrayField(
        verbose_name="Liste des noms de domaine d'e-mails",
        help_text="@entreprise.fr (sans le @)",
        base_field=models.CharField(max_length=255),
        blank=True,
        default=list,
    )

    created_at = models.DateTimeField(verbose_name="Date de création", default=timezone.now)
    updated_at = models.DateTimeField(verbose_name="Date de modification", auto_now=True)

    objects = models.Manager.from_queryset(CompanyQuerySet)()

    class Meta:
        verbose_name = "Entreprise"
        verbose_name_plural = "Entreprises"

    def __str__(self):
        return self.name

    def set_slug(self):
        """
        The slug field should be unique.
        """
        if not self.slug:
            self.slug = slugify(self.name)[:50]

    def save(self, *args, **kwargs):
        """Generate the slug field before saving."""
        self.set_slug()
        super().save(*args, **kwargs)

lemarche/cpv/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.template.defaultfilters import slugify
from django.utils import timezone


class CodeQuerySet(models.QuerySet):
    def has_sector(self):
        """Only return codes who have at least 1 Sector."""
        return self.prefetch_related("sectors").filter(sectors__isnull=False).distinct()


class Code(models.Model):
    name = models.CharField(verbose_name="Nom", max_length=255)
    slug = models.SlugField(verbose_name="Slug", max_length=255, unique=True)
    cpv_code = models.CharField(verbose_name="Code", max_length=8)
    hierarchy_level = models.IntegerField(
        verbose_name="Niveau hiérarchique", validators=[MinValueValidator(1), MaxValueValidator(7)]
    )

    sectors = models.ManyToManyField(
        "sectors.Sector", verbose_name="Secteurs d'activité", related_name="cpv_codes", blank=True
    )

    created_at = models.DateTimeField(verbose_name="Date de création", default=timezone.now)
    updated_at = models.DateTimeField(verbose_name="Date de modification", auto_now=True)

    objects = models.Manager.from_queryset(CodeQuerySet)()

    class Meta:
        verbose_name = "Code CPV"
        verbose_name_plural = "Code CPV"
        ordering = ["cpv_code"]

    def __str__(self):
        return f"{self.name} ({self.cpv_code})"

    def set_slug(self):
        """
        The slug field should be unique.
        """
        if not self.slug:
            self.slug = f"{str(self.cpv_code)}-{slugify(self.name)[:40]}"

    def set_hierarchy_level(self):
        """
        From 1 (XX000000) to 7 (XXXXXXXX).
        """
        if self.cpv_code:
            cpv_code_small = self.cpv_code[2:]
            self.hierarchy_level = len(cpv_code_small.rstrip("0")) + 1

    def save(self, *args, **kwargs):
        """Generate the slug field before saving."""
        self.set_slug()
        self.set_hierarchy_level()
        super().save(*args, **kwargs)

lemarche/labels/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.utils import timezone


class Label(models.Model):
    name = models.CharField(verbose_name="Nom", max_length=255)
    slug = models.SlugField(verbose_name="Slug", max_length=255, unique=True)
    description = models.TextField(verbose_name="Description", blank=True)
    website = models.URLField(verbose_name="Site web", blank=True)
    logo_url = models.URLField(verbose_name="Lien vers le logo", max_length=500, blank=True)

    data_description = models.TextField(verbose_name="Description de la source de données", blank=True)
    data_last_sync_date = models.DateTimeField("Date de dernière synchronisation", blank=True, null=True)

    logs = models.JSONField(verbose_name="Logs historiques", editable=False, default=list)

    created_at = models.DateTimeField(verbose_name="Date de création", default=timezone.now)
    updated_at = models.DateTimeField(verbose_name="Date de modification", auto_now=True)

    class Meta:
        verbose_name = "Label & certification"
        verbose_name_plural = "Labels & certifications"

    def __str__(self):
        return self.name

    def set_slug(self):
        """
        The slug field should be unique.
        """
        if not self.slug:
            self.slug = slugify(self.name)[:50]

    def save(self, *args, **kwargs):
        """Generate the slug field before saving."""
        self.set_slug()
        super().save(*args, **kwargs)

lemarche/cms/forms.py
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from wagtail.admin.forms import WagtailAdminPageForm


class ArticlePageForm(WagtailAdminPageForm):
    def clean(self):
        cleaned_data = super().clean()
        is_body_page = cleaned_data.get("body")
        is_static_page = cleaned_data.get("is_static_page") and cleaned_data.get("template_name")

        if not (is_body_page or is_static_page):
            self.add_error(
                self.error_class(error_class="nonfield"),
                """Vous devez définir un contenu pour l'article ou si c'est une page statique,
                appuyer sur la case à cocher et renseigner un nom de template valide""",
            )

        if is_static_page:
            template_name = cleaned_data.get("template_name")
            try:
                get_template(f"cms/static/{template_name}")
            except TemplateDoesNotExist:
                self.add_error(
                    "template_name",
                    """Vous devez entrer un nom de template qui existe.
                    En cas de soucis n'hésitez pas à contacter un développeur""",
                )
        return cleaned_data

lemarche/tenders/forms.py
from django import forms

from lemarche.tenders.models import Tender


class TenderAdminForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["contact_email_list"].delimiter = ";"  # Or whichever other character you want.

    class Meta:
        model = Tender
        fields = "__all__"

lemarche/users/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

from lemarche.users.models import User


class UserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("email",)


class UserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ("email",)

lemarche/www/conversations/forms.py
from django import forms

from lemarche.utils.mtcaptcha import check_captcha_token


class ContactForm(forms.Form):
    first_name = forms.CharField(
        label="Votre prénom", widget=forms.TextInput(attrs={"autofocus": "autofocus"}), required=True
    )
    last_name = forms.CharField(label="Votre nom", required=True)
    email = forms.EmailField(label="Votre email")
    subject = forms.CharField(max_length=200, label="Sujet de la demande")
    body_message = forms.CharField(label="Votre message", widget=forms.Textarea)

    def __init__(self, user=None, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        if user and user.is_authenticated:
            self.fields["first_name"].widget = forms.HiddenInput()
            self.fields["last_name"].widget = forms.HiddenInput()
            self.fields["email"].widget = forms.HiddenInput()

    def clean(self):
        super().clean()
        if not check_captcha_token(self.data):
            raise forms.ValidationError("Le code de protection est incorrect. Veuillez réessayer.")

lemarche/www/dashboard/forms.py
from django import forms

from lemarche.users.models import User


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["first_name", "last_name", "phone", "email"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Mandatory fields.
        self.fields["first_name"].required = True
        self.fields["last_name"].required = True
        self.fields["email"].required = True

        # Disabled fields
        self.fields["email"].disabled = True

lemarche/templates/cms/streams/card_feature.html
{% load theme_inclusion wagtailimages_tags %}
<div class="item">
    <div class="card c-card c-card--marche">
        <div class="card-header text-center">{% image self.image fill-150x150 class="img-fluid" %}</div>
        <div class="card-body">
            <p class="h4 lh-base">{{ self.title }}</p>
            <p>{{ self.subtitle }}</p>
        </div>
        <div class="card-footer text-right">
            <a href="{{ self.url }}"
               target="_blank"
               class="btn btn-link btn-ico stretched-link">
                <span>Découvrir</span>
                <i class="ri-arrow-right-up-line ri-lg"></i>
            </a>
        </div>
    </div>
</div>

lemarche/templates/cms/streams/image_with_link.html
{% load static wagtailimages_tags %}

<a href="{{self.external_link}}" target="_blank" rel="noopener">
    {% image self.image height-80 %}
</a>

lemarche/templates/cms/streams/section_our_features.html
{% load static bootstrap4 %}
{% load theme_inclusion wagtailcore_tags wagtailimages_tags %}
<section class="bg-gray-400">
    <div class="container py-4">
        <h2 class="h2 mb-3 mb-lg-5">{{ self.title }}</h2>
        <div class="row">
            <div class="col-md-12 px-0">
                <div class="multiCarousel px-0"
                     id="multiCarousel"
                     data-items="1,3,3,3"
                     data-slide="1"
                     data-interval="1000">
                    <div class="multiCarousel-inner">
                        {% for block in self.constats %}
                            {% include_block block %}
                        {% endfor %}
                    </div>
                    <div class="controls text-center">
                        <button class="btn btn-lg leftLst" href="#multiCarousel" data-slide="prev">
                            <i class="ri-arrow-left-line"></i>
                        </button>
                        <button class="btn btn-lg rightLst" href="#multiCarousel" data-slide="next">
                            <i class="ri-arrow-right-line"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

lemarche/templates/cms/streams/section_our_partners.html
{% load static bootstrap4 wagtailcore_tags wagtailimages_tags %}

<section class="s-hp-slider-partners">
    <div class="s-hp-slider-partners__container container">
        <div class="s-hp-slider-partners__row row">
            <div class="s-hp-slider-partners__col col-12">
                <h2 class="h2 mb-3 mb-lg-5 text-center">{{self.title}}</h2>
            </div>
        </div>
        <div class="s-hp-slider-partners__row row">
            {% for image_with_link in self.images_with_link  %}
                <div class="s-hp-slider-partners__col s-hp-slider-partners__col-image">
                    {% include_block image_with_link %}
                    {% comment %} <a href="https://group.bnpparibas/" target="_blank" rel="noopener">
                        <img src="{% static 'images/logo-partners-bnp.svg' %}" class="img-fluid" alt="Banque BNP Paribas | La banque d'un monde qui change" loading="lazy" />
                    </a> {% endcomment %}
                </div>
            {% endfor %}
        </div>
    </div>
</section>

lemarche/templates/cms/streams/section_our_ressources.html
{% load static bootstrap4 wagtailcore_tags %}

<section class="s-cards-grid-01 bg-gray-light">
    <div class="s-cards-grid-01__container container">
        <div class="s-cards-grid-01__row row">
            <div class="s-cards-grid-01__col s-cards-grid-01__col--title col-12">
                <h2 class="h2 mb-3 mb-lg-5">Nos ressources</h2>
            </div>
        </div>
        <div class="s-cards-grid-01__row row row-cols-1 row-cols-md-2 row-cols-lg-3">
            <div class="s-cards-grid-01__col col mb-3 mb-lg-5">
                <div class="card c-card has-one-link-inside h-100 w-100 c-card--marche">
                    <div class="card-header">
                        <img src="{% static 'img/hp-02-photo-06.min.jpg' %}" class="img-fluid img-fitcover" alt="" loading="lazy" />
                    </div>
                    <div class="card-body">
                        <p class="h3 lh-base">Les groupements</p>
                        <p>
                            Les groupements d'entreprises sociales inclusives sont des partenaires de choix, vous garantissant : une excellence dans l'exécution un interlocuteur unique tout au long de la prestation, un impact social fort.
                        </p>
                    </div>
                    <div class="card-footer text-right">
                        <a href="{% url 'pages:groupements' %}" id="track_home_groups" class="btn btn-link btn-ico stretched-link">
                            <span>Découvrir les groupements</span>
                            <i class="ri-arrow-right-up-line ri-lg"></i>
                        </a>
                    </div>
                </div>
            </div>
            <div class="s-cards-grid-01__col col mb-3 mb-lg-5">
                <div class="card c-card has-one-link-inside h-100 w-100 c-card--marche">
                    <div class="card-header">
                        <img src="{% static 'img/hp-02-photo-05.jpg' %}" class="img-fluid img-fitcover" alt="" loading="lazy" />
                    </div>
                    <div class="card-body">
                        <p class="h3 lh-sm">Valoriser vos achats</p>
                        <p><span class="badge badge-sm badge-pill badge-accent-01 text-white">J'achète inclusif</span></p>
                        <p>
                            Il se peut que vous travailliez déjà avec des entreprises sociales inclusives (insertion / handicap) sans le savoir. Retrouvez la liste complète des structures réferencées sur le marché
                        </p>
                    </div>
                    <div class="card-footer text-right">
                        <a href="{% url 'pages:valoriser_achats' %}" id="track_home_achats" class="btn btn-link btn-ico stretched-link">
                            <span>Découvrir la valorisation</span>
                            <i class="ri-arrow-right-up-line ri-lg"></i>
                        </a>
                    </div>
                </div>
            </div>
            <div class="s-cards-grid-01__col col mb-3 mb-lg-5">
                <div class="card c-card has-one-link-inside h-100 w-100 c-card--marche">
                    <div class="card-header">
                        <img src="{% static 'img/hp-02-photo-03.min.jpg' %}" class="img-fluid img-fitcover" alt="" loading="lazy" />
                    </div>
                    <div class="card-body">
                        <p class="h3 lh-sm">C’est quoi l’inclusion ?</p>
                        <p><span class="badge badge-sm badge-pill badge-accent-03 text-primary">Je gère ma structure</span></p>
                        <p>
                            Devenez acteur d’une société plus juste en orientant votre politique d’achat vers des structures d'insertion et du handicap qui luttent activement contre l'exclusion sociale.
                            Achetez inclusif !
                        </p>
                    </div>
                    <div class="card-footer text-right">
                        <a href="{% url 'pages:decouvrir_inclusion' %}" id="track_home_inclusion" class="btn btn-link btn-ico stretched-link">
                            <span class="ml-0">Découvrir l’inclusion</span>
                            <i class="ri-arrow-right-up-line ri-lg"></i>
                        </a>
                    </div>
                </div>
            </div>
            <div class="s-cards-grid-01__col col mb-3 mb-lg-5">
                <div class="card c-card has-one-link-inside h-100 w-100 c-card--marche">
                    <div class="card-header">
                        <img src="{% static 'img/hp-02-photo-04.min.jpg' %}" class="img-fluid img-fitcover" alt="" loading="lazy" />
                    </div>
                    <div class="card-body">
                        <p class="h3 lh-sm">Vous souhaitez être accompagné dans vos achats</p>
                        <p><span class="badge badge-sm badge-pill badge-accent-03 text-primary">Je gère ma structure</span></p>
                        <p>
                            Des organisations reconnues ont développé une expertise pour vous aider à aller plus loin dans votre démarche d'achat inclusif.
                            Découvrez-les !
                        </p>
                    </div>
                    <div class="card-footer text-right">
                        <a href="{% url 'pages:partenaires' %}" id="track_home_partners" class="btn btn-link btn-ico stretched-link">
                            <span>Découvrir des partenaires</span>
                            <i class="ri-arrow-right-up-line ri-lg"></i>
                        </a>
                    </div>
                </div>
            </div>
            <div class="s-cards-grid-01__col col mb-3 mb-lg-5">
                <div class="card c-card has-one-link-inside h-100 w-100 c-card--marche">
                    <div class="card-header">
                        <img src="{% static 'img/hp-02-photo-02.min.jpg' %}" class="img-fluid img-fitcover" alt="" loading="lazy" />
                    </div>
                    <div class="card-body">
                        <p class="h3 lh-sm">Acheteurs, alliez impact social et environnemental !</p>
                        <p><span class="badge badge-sm badge-pill badge-pilotage text-primary">Les actus du marché</span></p>
                        <p>
                            Quelques soient les déchets que produit votre entreprise, vous trouverez forcément un prestataire capable de répondre à vos besoins.
                        </p>
                    </div>
                    <div class="card-footer text-right">
                        <a href="{% url 'pages:filiere_recyclage' %}" id="track_home_recycling" class="btn btn-link btn-ico stretched-link">
                            <span>Découvrir le recyclage inclusif</span>
                            <i class="ri-arrow-right-up-line ri-lg"></i>
                        </a>
                    </div>
                </div>
            </div>
            <!-- Card CTA doit être la 6e (pour n'afficher que 2 lignes de ressources) -->
            <div class="s-cards-grid-01__col col mb-3 mb-lg-5">
                <div class="card c-card has-one-link-inside h-100 w-100 c-card--marche">
                    <div class="card-body d-flex align-items-center">
                        <div class="w-100 text-center py-5">
                            <p class="h3 lh-sm">Découvrez toutes nos ressources</p>
                            <a href="{% slugurl 'ressources' %}" id="track_home_ressources" class="btn btn-primary btn-sm btn-ico stretched-link">
                                <i class="ri-search-eye-line ri-lg"></i>
                                <span>Découvrir</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

lemarche/templates/cms/streams/section_our_siaes.html
{% load static %}

<section class="bg-gray-light py-5">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-md-8 my-sm-auto">
                <img src="{% static 'images/hp-logos-labels.min.png' %}" class="img-fluid" loading="lazy" alt="Logos de différents labels et certifications">
            </div>
            <div class="col-sm-6 col-md-4 my-4 my-sm-auto">
                <h2 class="h2 mb-3 mb-lg-5">{{self.title}}</h2>
                {{self.subtitle}}
                <a href="{% url 'tenders:create' %}" id="home-siaes-labels" class="btn btn-primary d-block d-md-inline-block mb-2">
                    <i class="ri-mail-send-line mr-2"></i>Publier un besoin d'achat
                </a>
            </div>
        </div>
    </div>
</section>

lemarche/templates/cms/streams/stats_website.html
<section class="s-section m-0 bg-nuance-09">
    <div class="s-section__container container">
        <div class="s-section__row row">
            <div class="s-section__col col-12 py-5">
                <h2 class="h2 m-0">
                    Grâce à vos achats, <strong class="text-important">17 714</strong> personnes éloignées de l'emploi ou en situation de handicap
                    ont été recrutées au mois de Mars 2023 par nos prestataires inclusifs.
                </h2>
            </div>
        </div>
    </div>
</section>