config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from wagtail import urls as wagtail_urls
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.documents import urls as wagtaildocs_urls

from lemarche.utils.admin.admin_site import admin_site


urlpatterns = [
    path("admin/", admin_site.urls),
    path("api/", include("lemarche.api.urls")),
    path("accounts/", include("lemarche.www.auth.urls")),
    path("besoins/", include("lemarche.www.tenders.urls")),
    path("prestataires/", include("lemarche.www.siaes.urls")),
    path("profil/", include("lemarche.www.dashboard.urls")),
    path("profil/prestataires/", include("lemarche.www.dashboard_siaes.urls")),
    path("profil/reseaux/", include("lemarche.www.dashboard_networks.urls")),
    path("profil/listes-dachats/", include("lemarche.www.dashboard_favorites.urls")),
    path("select2/", include("django_select2.urls")),
    # admin blog
    path("cms/", include(wagtailadmin_urls)),
    # url docuemnts of glog
    path("documents/", include(wagtaildocs_urls)),
    # urls pages blog
    path("", include("lemarche.www.pages.urls")),
    path("", include(wagtail_urls)),
]

if settings.DEBUG and "debug_toolbar" in settings.INSTALLED_APPS:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

if settings.BITOUBI_ENV in (
    "dev",
    "review_app",
):
    urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + urlpatterns

itou_c4_api/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [path("admin/", admin.site.urls), path("", include("itou_c4_api.c4_directory.urls"))] + static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
)

lemarche/api/urls.py
from django.urls import path
from django.views.generic import RedirectView, TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
from rest_framework import routers

from lemarche.api.emails.views import InboundParsingEmailView
from lemarche.api.networks.views import NetworkViewSet
from lemarche.api.perimeters.views import PerimeterAutocompleteViewSet, PerimeterKindViewSet, PerimeterViewSet
from lemarche.api.sectors.views import SectorViewSet
from lemarche.api.siaes.views import SiaeKindViewSet, SiaePrestaTypeViewSet, SiaeViewSet
from lemarche.api.tenders.views import TenderAmountViewSet, TenderKindViewSet, TenderViewSet


# https://docs.djangoproject.com/en/dev/topics/http/urls/#url-namespaces-and-included-urlconfs
app_name = "api"

router = routers.DefaultRouter()
router.register(r"siae/kinds", SiaeKindViewSet, basename="siae-kinds")
router.register(r"siae/presta-types", SiaePrestaTypeViewSet, basename="siae-presta-types")
router.register(r"siae", SiaeViewSet, basename="siae")
router.register(r"sectors", SectorViewSet, basename="sectors")
router.register(r"networks", NetworkViewSet, basename="networks")
router.register(r"perimeters/kinds", PerimeterKindViewSet, basename="perimeter-kinds")
router.register(r"perimeters/autocomplete", PerimeterAutocompleteViewSet, basename="perimeters-autocomplete")
router.register(r"perimeters", PerimeterViewSet, basename="perimeters")
router.register(r"tenders/kinds", TenderKindViewSet, basename="tender-kinds")
router.register(r"tenders/amounts", TenderAmountViewSet, basename="tender-amounts")
router.register(r"tenders", TenderViewSet, basename="tenders")

urlpatterns = [
    path("", TemplateView.as_view(template_name="api/home.html"), name="home"),
    # Additional API endpoints
    path("siae/slug/<str:slug>/", SiaeViewSet.as_view({"get": "retrieve_by_slug"}), name="siae-retrieve-by-slug"),
    path("siae/siret/<str:siret>/", SiaeViewSet.as_view({"get": "retrieve_by_siret"}), name="siae-retrieve-by-siret"),
    path(
        "siaes/siret/<str:siret>/",
        RedirectView.as_view(pattern_name="api:siae-retrieve-by-siret", permanent=True),
        name="old_api_siae_siret",
    ),
    path("inbound-email-parsing/", InboundParsingEmailView.as_view(), name="inbound-email-parsing"),
    # Swagger / OpenAPI documentation
    path("schema/", SpectacularAPIView.as_view(), name="schema"),
    path("docs/", SpectacularSwaggerView.as_view(url_name="api:schema"), name="swagger-ui"),
    path("redoc/", SpectacularRedocView.as_view(url_name="api:schema"), name="redoc"),
]

urlpatterns += router.urls

lemarche/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [path("admin/", admin.site.urls), path("", include("lemarche.api.urls"))] + static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
)

lemarche/www/dashboard/urls.py
from django.urls import path

from lemarche.www.dashboard.views import DashboardHomeView, ProfileEditView


app_name = "dashboard"

urlpatterns = [
    path("", DashboardHomeView.as_view(), name="home"),
    path("modifier/", ProfileEditView.as_view(), name="profile_edit"),
    # FavoriteList
    # see dashboard_favorites/urls.py
    # Network
    # see dashboard_networks/urls.py
    # Adopt Siae, Edit Siae & Siae Users
    # see dashboard_siaes/urls.py
]

lemarche/www/dashboard_favorites/urls.py
from django.urls import path

from lemarche.www.dashboard_favorites.views import (
    DashboardFavoriteItemDeleteView,
    DashboardFavoriteListCreateView,
    DashboardFavoriteListDeleteView,
    DashboardFavoriteListDetailView,
    DashboardFavoriteListEditView,
    DashboardFavoriteListView,
)


app_name = "dashboard_favorites"

urlpatterns = [
    path("", DashboardFavoriteListView.as_view(), name="list"),
    path("creer/", DashboardFavoriteListCreateView.as_view(), name="list_create"),
    path("<str:slug>/", DashboardFavoriteListDetailView.as_view(), name="list_detail"),
    path(
        "<slug:slug>/prestataires/<slug:siae_slug>/",
        DashboardFavoriteItemDeleteView.as_view(),
        name="item_delete",
    ),
    path("<str:slug>/modifier/", DashboardFavoriteListEditView.as_view(), name="list_edit"),
    path(
        "<str:slug>/supprimer/",
        DashboardFavoriteListDeleteView.as_view(),
        name="list_delete",
    ),
]

lemarche/www/siae/urls.py
from django.urls import path

from lemarche.www.siae.views import SiaeDetailView, SiaeSearchResultsDownloadView, SiaeSearchResultsView


# https://docs.djangoproject.com/en/dev/topics/http/urls/#url-namespaces-and-included-urlconfs
app_name = "siae"

urlpatterns = [
    path("", SiaeSearchResultsView.as_view(), name="search_results"),
    path("download/", SiaeSearchResultsDownloadView.as_view(), name="search_results_download"),
    path("<str:slug>/", SiaeDetailView.as_view(), name="detail"),
]

lemarche/www/siaes/urls.py
from django.urls import path

from lemarche.www.siaes.views import (
    SiaeDetailView,
    SiaeFavoriteView,
    SiaeSearchResultsDownloadView,
    SiaeSearchResultsView,
)


# https://docs.djangoproject.com/en/dev/topics/http/urls/#url-namespaces-and-included-urlconfs
app_name = "siae"

urlpatterns = [
    path("", SiaeSearchResultsView.as_view(), name="search_results"),
    path("download/", SiaeSearchResultsDownloadView.as_view(), name="search_results_download"),
    path("<str:slug>/", SiaeDetailView.as_view(), name="detail"),
    path("<str:slug>/favoris/", SiaeFavoriteView.as_view(), name="favorite_lists"),
]

lemarche/companies/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.utils import timezone
from django_better_admin_arrayfield.models.fields import ArrayField


class CompanyQuerySet(models.QuerySet):
    def has_user(self):
        return self.filter(users__isnull=False).distinct()

    def has_email_domain(self):
        return self.exclude(email_domain_list=[])


class Company(models.Model):
    name = models.CharField(verbose_name="Nom", max_length=255)
    slug = models.SlugField(verbose_name="Slug", max_length=255, unique=True)
    description = models.TextField(verbose_name="Description", blank=True)
    siret = models.CharField(verbose_name="Siret", max_length=14, blank=True)
    website = models.URLField(verbose_name="Site web", blank=True)
    logo_url = models.URLField(verbose_name="Lien vers le logo", max_length=500, blank=True)

    email_domain_list = ArrayField(
        verbose_name="Liste des noms de domaine d'e-mails",
        help_text="@entreprise.fr (sans le @)",
        base_field=models.CharField(max_length=255),
        blank=True,
        default=list,
    )

    created_at = models.DateTimeField(verbose_name="Date de création", default=timezone.now)
    updated_at = models.DateTimeField(verbose_name="Date de modification", auto_now=True)

    objects = models.Manager.from_queryset(CompanyQuerySet)()

    class Meta:
        verbose_name = "Entreprise"
        verbose_name_plural = "Entreprises"

    def __str__(self):
        return self.name

    def set_slug(self):
        """
        The slug field should be unique.
        """
        if not self.slug:
            self.slug = slugify(self.name)[:50]

    def save(self, *args, **kwargs):
        """Generate the slug field before saving."""
        self.set_slug()
        super().save(*args, **kwargs)

lemarche/cpv/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.template.defaultfilters import slugify
from django.utils import timezone


class CodeQuerySet(models.QuerySet):
    def has_sector(self):
        """Only return codes who have at least 1 Sector."""
        return self.prefetch_related("sectors").filter(sectors__isnull=False).distinct()


class Code(models.Model):
    name = models.CharField(verbose_name="Nom", max_length=255)
    slug = models.SlugField(verbose_name="Slug", max_length=255, unique=True)
    cpv_code = models.CharField(verbose_name="Code", max_length=8)
    hierarchy_level = models.IntegerField(
        verbose_name="Niveau hiérarchique", validators=[MinValueValidator(1), MaxValueValidator(7)]
    )

    sectors = models.ManyToManyField(
        "sectors.Sector", verbose_name="Secteurs d'activité", related_name="cpv_codes", blank=True
    )

    created_at = models.DateTimeField(verbose_name="Date de création", default=timezone.now)
    updated_at = models.DateTimeField(verbose_name="Date de modification", auto_now=True)

    objects = models.Manager.from_queryset(CodeQuerySet)()

    class Meta:
        verbose_name = "Code CPV"
        verbose_name_plural = "Code CPV"
        ordering = ["cpv_code"]

    def __str__(self):
        return f"{self.name} ({self.cpv_code})"

    def set_slug(self):
        """
        The slug field should be unique.
        """
        if not self.slug:
            self.slug = f"{str(self.cpv_code)}-{slugify(self.name)[:40]}"

    def set_hierarchy_level(self):
        """
        From 1 (XX000000) to 7 (XXXXXXXX).
        """
        if self.cpv_code:
            cpv_code_small = self.cpv_code[2:]
            self.hierarchy_level = len(cpv_code_small.rstrip("0")) + 1

    def save(self, *args, **kwargs):
        """Generate the slug field before saving."""
        self.set_slug()
        self.set_hierarchy_level()
        super().save(*args, **kwargs)

lemarche/favorites/models.py
from uuid import uuid4

from django.conf import settings
from django.db import models
from django.db.models.signals import post_delete, post_save
from django.dispatch import receiver
from django.template.defaultfilters import slugify
from django.utils import timezone


class FavoriteListQuerySet(models.QuerySet):
    def by_user(self, user):
        return self.filter(user=user)


class FavoriteList(models.Model):
    name = models.CharField(verbose_name="Nom", max_length=255)
    slug = models.SlugField(verbose_name="Slug", max_length=255, unique=True)

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name="Utilisateur", related_name="favorite_lists", on_delete=models.CASCADE
    )
    siaes = models.ManyToManyField(
        "siaes.Siae",
        through="favorites.FavoriteItem",
        verbose_name="Structures en favoris",
        related_name="favorite_lists",
        blank=True,
    )

    created_at = models.DateTimeField(verbose_name="Date de création", default=timezone.now)
    updated_at = models.DateTimeField(verbose_name="Date de modification", auto_now=True)

    objects = models.Manager.from_queryset(FavoriteListQuerySet)()

    class Meta:
        verbose_name = "Liste de favoris"
        verbose_name_plural = "Listes de favoris"

    def __str__(self):
        return self.name

    def set_slug(self):
        """
        The slug field should be unique.
        """
        if not self.slug:
            self.slug = f"{slugify(self.name)[:40]}-{str(uuid4())[:4]}"

    def save(self, *args, **kwargs):
        """Generate the slug field before saving."""
        self.set_slug()
        super().save(*args, **kwargs)


@receiver(post_save, sender=FavoriteList)
@receiver(post_delete, sender=FavoriteList)
def favorite_list_changed(sender, instance, **kwargs):
    """
    Will be called when we create, update or delete a Favorite List
    """
    instance.user.favorite_list_count = instance.user.favorite_lists.count()
    instance.user.save()


class FavoriteItem(models.Model):
    siae = models.ForeignKey("siaes.Siae", verbose_name="Structure", on_delete=models.CASCADE)
    favorite_list = models.ForeignKey(
        "favorites.FavoriteList", verbose_name="Liste de favoris", on_delete=models.CASCADE
    )

    created_at = models.DateTimeField(verbose_name="Date de création", default=timezone.now)
    updated_at = models.DateTimeField(verbose_name="Date de modification", auto_now=True)

    class Meta:
        verbose_name = "Structure en favoris"
        verbose_name_plural = "Structures en favoris"
        ordering = ["-created_at"]

lemarche/cms/forms.py
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from wagtail.admin.forms import WagtailAdminPageForm


class ArticlePageForm(WagtailAdminPageForm):
    def clean(self):
        cleaned_data = super().clean()
        is_body_page = cleaned_data.get("body")
        is_static_page = cleaned_data.get("is_static_page") and cleaned_data.get("template_name")

        if not (is_body_page or is_static_page):
            self.add_error(
                self.error_class(error_class="nonfield"),
                """Vous devez définir un contenu pour l'article ou si c'est une page statique,
                appuyer sur la case à cocher et renseigner un nom de template valide""",
            )

        if is_static_page:
            template_name = cleaned_data.get("template_name")
            try:
                get_template(f"cms/static/{template_name}")
            except TemplateDoesNotExist:
                self.add_error(
                    "template_name",
                    """Vous devez entrer un nom de template qui existe.
                    En cas de soucis n'hésitez pas à contacter un développeur""",
                )
        return cleaned_data

lemarche/tenders/forms.py
from django import forms

from lemarche.tenders.models import Tender


class TenderAdminForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["contact_email_list"].delimiter = ";"  # Or whichever other character you want.

    class Meta:
        model = Tender
        fields = "__all__"

lemarche/users/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

from lemarche.users.models import User


class UserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("email",)


class UserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ("email",)

lemarche/www/conversations/forms.py
from django import forms

from lemarche.utils.mtcaptcha import check_captcha_token


class ContactForm(forms.Form):
    first_name = forms.CharField(
        label="Votre prénom", widget=forms.TextInput(attrs={"autofocus": "autofocus"}), required=True
    )
    last_name = forms.CharField(label="Votre nom", required=True)
    email = forms.EmailField(label="Votre email")
    subject = forms.CharField(max_length=200, label="Sujet de la demande")
    body_message = forms.CharField(label="Votre message", widget=forms.Textarea)

    def __init__(self, user=None, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        if user and user.is_authenticated:
            self.fields["first_name"].widget = forms.HiddenInput()
            self.fields["last_name"].widget = forms.HiddenInput()
            self.fields["email"].widget = forms.HiddenInput()

    def clean(self):
        super().clean()
        if not check_captcha_token(self.data):
            raise forms.ValidationError("Le code de protection est incorrect. Veuillez réessayer.")

lemarche/www/dashboard/forms.py
from django import forms

from lemarche.users.models import User


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["first_name", "last_name", "phone", "email"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Mandatory fields.
        self.fields["first_name"].required = True
        self.fields["last_name"].required = True
        self.fields["email"].required = True

        # Disabled fields
        self.fields["email"].disabled = True

lemarche/templates/favorites/_favorite_item_add_modal.html
<div class="modal fade modal-siae" id="favorite_item_add_modal" tabindex="-1" role="dialog" aria-modal="true" data-backdrop="static" data-keyboard="false" aria-labelledby="modalTitle">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" id="modalTitle">Liste d'achat favoris</h3>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fermer">
                    <i class="ri-close-line"></i>
                </button>
            </div>

            <!-- New list -->
            <form method="POST" action="{% url 'siae:favorite_lists' siae.slug|default:'siae-slug-to-replace' %}">
                {% csrf_token %}
                <div class="modal-body home-content-body">
                    <label class="mb-2 d-inline-block font-weight-bold" for="id_new_favorite_list">Créer une {% if user.favorite_list_count %}nouvelle {% endif %}liste</label>
                    <div class="form-row">
                        <div class="form-group col mb-0">
                            <input type="text" name="new_favorite_list" id="id_new_favorite_list" class="form-control form-control-sm" placeholder="Entretien des locaux, achat de masque…" required>
                        </div>
                        <div class="form-group col-auto mb-0">
                            <button class="btn btn-sm {% if user.favorite_list_count %}btn-outline-primary{% else %}btn-primary{% endif %}" type="submit" name="action" value="create">Créer</button>
                        </div>
                    </div>
                </div>
            </form>

            <!-- Existing list(s) -->
            {% if user.favorite_list_count %}
                <form method="POST" action="{% url 'siae:favorite_lists' siae.slug|default:'siae-slug-to-replace' %}">
                    {% csrf_token %}
                    <div class="modal-body home-content-body pt-0">
                        <hr data-text="ou" />
                        <div class="form-group">
                            <label>Choisir une liste existante</label>
                            <ul class="list-group">
                            {% for favorite_list in user.favorite_lists.all %}
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    <div class="custom-control custom-radio w-100">
                                        <input class="custom-control-input" type="radio" name="favorite_list" value="{{ favorite_list.id }}" id="{{ favorite_list.id }}" required>
                                        <label class="custom-control-label white-space-nowrap d-block" for="{{ favorite_list.id }}">{{ favorite_list.name }}</label>
                                    </div>
                                    <span class="fs-xs badge badge-marche-light badge-pill">{{ favorite_list.siaes.count }}</span>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-sm btn-primary" type="submit" name="action" value="add">Enregistrer</button>
                    </div>
                </form>
            {% endif %}
        </div>
    </div>
</div>

lemarche/templates/favorites/_favorite_item_remove_modal.html
<div class="modal fade modal-siae" id="favorite_item_remove_modal" tabindex="-1" role="dialog" aria-modal="true" data-backdrop="static" data-keyboard="false" aria-labelledby="modalTitle">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" id="modalTitle">Supprimer</h3>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fermer">
                    <i class="ri-close-line"></i>
                </button>
            </div>
            <form method="POST" action="{% url 'dashboard_favorites:item_delete' favorite_list.slug|default:'favorite-list-slug' siae.slug|default:'siae-slug-to-replace' %}">
                {% csrf_token %}
                <div class="modal-body home-content-body">
                    <p class="font-weight-bold">
                        Supprimer la structure <strong>{% if siae %}{{ siae.name_display }}{% else %}<span id="siae-name-display"></span>{% endif %}</strong> de votre liste d'achat ?
                    </p>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-sm btn-outline-primary" type="button" data-dismiss="modal" aria-label="Fermer">Annuler</button>
                    <button class="btn btn-sm btn-primary" type="submit">Confirmer</button>
                </div>
            </form>
        </div>
    </div>
</div>

lemarche/templates/favorites/dashboard_favorite_list.html
{% extends "layouts/base.html" %}
{% load bootstrap4 %}

{% block title %}Liste d'achat favoris{{ block.super }}{% endblock %}

{% block breadcrumbs %}
<section>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav class="c-breadcrumb c-breadcrumb--marche" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'wagtail_serve' '' %}">Accueil</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'dashboard:home' %}">Tableau de bord</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Liste d'achat favoris</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block content %}
<section class="s-section">
    <div class="s-section__container container">
        <div class="row">
            <div class="col-12 col-lg-8">
                <h1 class="h1 mb-3 mb-lg-5">
                    <strong>Liste d'achat favoris</strong>
                </h1>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-lg-8">
                <!-- New list -->
                <h2>Nouvelle liste</h2>
                <form method="POST" action="{% url 'dashboard_favorites:list_create' %}">
                    {% csrf_token %}
                    {% bootstrap_form_errors form type="all" %}
                    <label class="mb-2 d-inline-block font-weight-bold" for="id_name">Créer une {% if favorite_lists.count %}nouvelle {% endif %}liste</label>
                    <div class="form-row">
                        <div class="form-group col">
                            {% bootstrap_field form.name show_label=False %}
                        </div>
                        <div class="form-group col-auto">
                            <button class="btn btn-primary btn-ico" type="submit" name="action" value="create">
                                <span>Créer</span>
                                <i class="ri-add-fill ri-lg"></i>
                            </button>
                        </div>
                    </div>
                </form>

                <!-- Existing list(s) -->
                {% if favorite_lists.count %}
                    <h2>{{ favorite_lists.count }} liste{% if favorite_lists.count > 1 %}s{% endif %} existante{% if favorite_lists.count > 1 %}s{% endif %}</h2>
                    <ul class="list-group">
                    {% for favorite_list in favorite_lists.all %}
                        <li class="list-group-item">
                            <a href="{% url 'dashboard_favorites:list_detail' favorite_list.slug %}" class="d-flex justify-content-between align-items-center text-decoration-none" title="Voir la liste">
                                <span>{{ favorite_list.name }} <span class="ml-2 fs-xs badge badge-marche-light badge-pill">{{ favorite_list.siaes.count }}</span></span>
                                <i class="ri-eye-line ri-lg"></i>
                            </a>
                        </li>
                    {% endfor %}
                    </ul>
                {% else %}
                    <p class="text-danger font-weight-bold">Vous n'avez pas encore créé de listes !</p>
                {% endif %}
            </div>
        </div>

    </div>
</section>
{% endblock %}

lemarche/templates/favorites/dashboard_favorite_list_detail.html
{% extends "layouts/base.html" %}
{% load static %}

{% block title %}{{ favorite_list.name }} - Liste d'achat favoris{{ block.super }}{% endblock %}

{% block breadcrumbs %}
<section>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav class="c-breadcrumb c-breadcrumb--marche" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'wagtail_serve' '' %}">Accueil</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'dashboard:home' %}">Tableau de bord</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'dashboard_favorites:list' %}">Liste d'achat favoris</a></li>
                        <li class="breadcrumb-item active" aria-current="page" title="{{ favorite_list.name }}">{{ favorite_list.name }}</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block content %}
<section class="s-section">
    <div class="s-section__container container">
        <div class="row">
            <div class="col-12 col-lg-8">
                <h1 class="h1 mb-3 mb-lg-5 d-flex justify-content-between">
                    <strong>{{ favorite_list.name }}</strong>
                    <div class="btn-group" role="group" aria-label="Actions sur la liste de favoris">
                        <button class="btn btn-link btn-ico text-decoration-none" data-toggle="modal" data-target="#favorite_list_edit_modal" title="Editer la liste">
                            <i class="ri-pencil-fill ri-lg font-weight-light"></i>
                        </button>
                        <button class="btn btn-link btn-ico text-decoration-none" data-toggle="modal" data-target="#favorite_list_delete_modal" title="Supprimer la liste">
                            <i class="ri-delete-bin-6-line ri-lg font-weight-light"></i>
                        </button>
                    </div>
                </h1>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-lg-8">
                {% if favorite_list.siaes.count == 0 %}
                    <p class="text-danger font-weight-bold" role="status">Vous n'avez pas encore ajouté de structures à cette liste !</p>
                {% endif %}
                {% for siae in favorite_list.siaes.all %}
                    {% include "siaes/_card_search_result.html" with siae=siae from_profile="true" %}
                {% endfor %}
            </div>
            <div class="col-12 col-lg-4">
                <div class="btn-group w-100 mb-3">
                    <a href="{% url 'siae:search_results_download' %}?favorite_list={{ favorite_list.slug }}&format=xls" id="favorite-list-export-xls" class="btn btn-outline-primary btn-ico btn-block {% if favorite_list.siaes.count == 0 %}disabled{% endif %}" target="_blank">
                        <span>Télécharger la liste (.xls)</span>
                        <i class="ri-download-line ri-lg"></i>
                    </a>
                    <button type="button" class="btn btn-outline-primary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="sr-only">Plus d'options de téléchargement</span>
                    </button>
                    <div class="dropdown-menu dropdown-menu-right">
                        <a href="{% url 'siae:search_results_download' %}?favorite_list={{ favorite_list.slug }}&format=csv" id="favorite-list-export-csv" class="dropdown-item {% if favorite_list.siaes.count == 0 %}disabled{% endif %}" target="_blank">
                            Télécharger la liste (.csv)
                        </a>
                    </div>
                </div>
                <a href="{% url 'tenders:create' %}" id="favorite-list-create-btn" class="btn btn-primary w-100 btn-ico mt-2">
                    <i class="ri-add-fill ri-lg mr-2"></i>Publier un besoin d'achat
                </a>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block modals %}
    {% include "favorites/_favorite_item_remove_modal.html" with favorite_list=favorite_list %}
    {% include "favorites/_favorite_list_edit_modal.html" with favorite_list=favorite_list %}
    {% include "favorites/_favorite_list_delete_modal.html" with favorite_list=favorite_list %}
{% endblock %}

{% block extra_js %}
<script type="text/javascript" src="{% static 'js/favorite_item_remove.js' %}"></script>
{% endblock %}