config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from wagtail import urls as wagtail_urls
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.documents import urls as wagtaildocs_urls

from lemarche.utils.admin.admin_site import admin_site


urlpatterns = [
    path("admin/", admin_site.urls),
    path("api/", include("lemarche.api.urls")),
    path("accounts/", include("lemarche.www.auth.urls")),
    path("besoins/", include("lemarche.www.tenders.urls")),
    path("prestataires/", include("lemarche.www.siaes.urls")),
    path("profil/", include("lemarche.www.dashboard.urls")),
    path("profil/prestataires/", include("lemarche.www.dashboard_siaes.urls")),
    path("profil/reseaux/", include("lemarche.www.dashboard_networks.urls")),
    path("profil/listes-dachats/", include("lemarche.www.dashboard_favorites.urls")),
    path("select2/", include("django_select2.urls")),
    # admin blog
    path("cms/", include(wagtailadmin_urls)),
    # url docuemnts of glog
    path("documents/", include(wagtaildocs_urls)),
    # urls pages blog
    path("", include("lemarche.www.pages.urls")),
    path("", include(wagtail_urls)),
]

if settings.DEBUG and "debug_toolbar" in settings.INSTALLED_APPS:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

if settings.BITOUBI_ENV in (
    "dev",
    "review_app",
):
    urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + urlpatterns

itou_c4_api/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [path("admin/", admin.site.urls), path("", include("itou_c4_api.c4_directory.urls"))] + static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
)

lemarche/api/urls.py
from django.urls import path
from django.views.generic import RedirectView, TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
from rest_framework import routers

from lemarche.api.emails.views import InboundParsingEmailView
from lemarche.api.networks.views import NetworkViewSet
from lemarche.api.perimeters.views import PerimeterAutocompleteViewSet, PerimeterKindViewSet, PerimeterViewSet
from lemarche.api.sectors.views import SectorViewSet
from lemarche.api.siaes.views import SiaeKindViewSet, SiaePrestaTypeViewSet, SiaeViewSet
from lemarche.api.tenders.views import TenderAmountViewSet, TenderKindViewSet, TenderViewSet


# https://docs.djangoproject.com/en/dev/topics/http/urls/#url-namespaces-and-included-urlconfs
app_name = "api"

router = routers.DefaultRouter()
router.register(r"siae/kinds", SiaeKindViewSet, basename="siae-kinds")
router.register(r"siae/presta-types", SiaePrestaTypeViewSet, basename="siae-presta-types")
router.register(r"siae", SiaeViewSet, basename="siae")
router.register(r"sectors", SectorViewSet, basename="sectors")
router.register(r"networks", NetworkViewSet, basename="networks")
router.register(r"perimeters/kinds", PerimeterKindViewSet, basename="perimeter-kinds")
router.register(r"perimeters/autocomplete", PerimeterAutocompleteViewSet, basename="perimeters-autocomplete")
router.register(r"perimeters", PerimeterViewSet, basename="perimeters")
router.register(r"tenders/kinds", TenderKindViewSet, basename="tender-kinds")
router.register(r"tenders/amounts", TenderAmountViewSet, basename="tender-amounts")
router.register(r"tenders", TenderViewSet, basename="tenders")

urlpatterns = [
    path("", TemplateView.as_view(template_name="api/home.html"), name="home"),
    # Additional API endpoints
    path("siae/slug/<str:slug>/", SiaeViewSet.as_view({"get": "retrieve_by_slug"}), name="siae-retrieve-by-slug"),
    path("siae/siret/<str:siret>/", SiaeViewSet.as_view({"get": "retrieve_by_siret"}), name="siae-retrieve-by-siret"),
    path(
        "siaes/siret/<str:siret>/",
        RedirectView.as_view(pattern_name="api:siae-retrieve-by-siret", permanent=True),
        name="old_api_siae_siret",
    ),
    path("inbound-email-parsing/", InboundParsingEmailView.as_view(), name="inbound-email-parsing"),
    # Swagger / OpenAPI documentation
    path("schema/", SpectacularAPIView.as_view(), name="schema"),
    path("docs/", SpectacularSwaggerView.as_view(url_name="api:schema"), name="swagger-ui"),
    path("redoc/", SpectacularRedocView.as_view(url_name="api:schema"), name="redoc"),
]

urlpatterns += router.urls

lemarche/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [path("admin/", admin.site.urls), path("", include("lemarche.api.urls"))] + static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
)

lemarche/www/auth/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from lemarche.www.auth.views import LoginView, PasswordResetView, SignupView


# https://docs.djangoproject.com/en/dev/topics/http/urls/#url-namespaces-and-included-urlconfs
app_name = "auth"

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(template_name="auth/logged_out.html"), name="logout"),
    path("signup/", SignupView.as_view(), name="signup"),
    path("password-reset/", PasswordResetView.as_view(), name="password_reset"),
    path(
        "password-reset/sent/",
        auth_views.PasswordResetDoneView.as_view(template_name="auth/password_reset_sent.html"),
        name="password_reset_sent",
    ),  # name="password_reset_done"
    path(
        "password-reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="auth/password_reset_confirm.html", success_url=reverse_lazy("auth:password_reset_complete")
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/done/",
        auth_views.PasswordResetCompleteView.as_view(template_name="auth/password_reset_complete.html"),
        name="password_reset_complete",
    ),
]

lemarche/www/pages/urls.py
from django.urls import path
from django.views.generic import TemplateView

from lemarche.www.pages.views import (
    CompanyReferenceCalculatorView,
    ContactView,
    HomeView,
    ImpactCalculatorView,
    PageView,
    SiaeGroupListView,
    SocialImpactBuyersCalculatorView,
    StatsView,
    TrackView,
    trigger_error,
)


# https://docs.djangoproject.com/en/dev/topics/http/urls/#url-namespaces-and-included-urlconfs
app_name = "pages"

urlpatterns = [
    path("ancien_accueil", HomeView.as_view(), name="home"),
    path("contact/", ContactView.as_view(), name="contact"),
    # Calculator endpoints
    path("calibrer-achat-socialement-responsable/", ImpactCalculatorView.as_view(), name="impact_calculator"),
    path(
        "calculer-impact-social-achat-inclusif/",
        SocialImpactBuyersCalculatorView.as_view(),
        name="buyer_social_impact_calculator",
    ),
    path("acheteurs-reference-client/", CompanyReferenceCalculatorView.as_view(), name="company_reference_calculator"),
    # Other dynamic pages
    path("groupements/", SiaeGroupListView.as_view(), name="groupements"),
    path("stats/", StatsView.as_view(), name="stats"),
    # Static pages
    path(
        "filiere/restauration/",
        TemplateView.as_view(template_name="pages/filiere_restauration.html"),
        name="filiere_restauration",
    ),
    path(
        "filiere/recyclage/",
        TemplateView.as_view(template_name="pages/filiere_recyclage.html"),
        name="filiere_recyclage",
    ),
    path(
        "decouvrir-inclusion/",
        TemplateView.as_view(template_name="pages/decouvrir-inclusion.html"),
        name="decouvrir_inclusion",
    ),
    path(
        "partenaires/",
        TemplateView.as_view(template_name="pages/partenaires.html"),
        name="partenaires",
    ),
    path(
        "valoriser-achats/",
        TemplateView.as_view(template_name="pages/valoriser-achats.html"),
        name="valoriser_achats",
    ),
    path(
        "accessibilite/",
        TemplateView.as_view(template_name="pages/accessibilite.html"),
        name="accessibilite",
    ),
    # Sentry endpoint for frontend errors
    path("sentry-debug/", trigger_error, name="sentry_debug"),
    # Tracking endpoint for the frontend
    path("track/", TrackView.as_view(), name="track_frontend"),
    # Flatpages (created in the admin: faq, qui-sommes-nous, cgu, confidentialité)
    # TODO: move to wagtail?
    # path("", include("django.contrib.flatpages.urls")),
    # path("<path:url>", PageView.as_view(), name="flatpage"),  # conflict with wagtail_urls
    path("qui-sommes-nous/", PageView.as_view(), {"url": "/qui-sommes-nous/"}, name="qui-sommes-nous"),
    path("faq/", PageView.as_view(), {"url": "/faq/"}, name="faq"),
    path(
        "2021-10-06-le-marche-fait-peau-neuve/",
        PageView.as_view(),
        {"url": "/2021-10-06-le-marche-fait-peau-neuve/"},
        name="2021-10-06-le-marche-fait-peau-neuve",
    ),
    path("mentions-legales/", PageView.as_view(), {"url": "/mentions-legales/"}, name="mentions-legales"),
    path("cgu/", PageView.as_view(), {"url": "/cgu/"}, name="cgu"),
    path("cgu-api/", PageView.as_view(), {"url": "/cgu-api/"}, name="cgu-api"),
    path("confidentialite/", PageView.as_view(), {"url": "/confidentialite/"}, name="confidentialite"),
    # Error pages
    path("403/", TemplateView.as_view(template_name="403.html"), name="403"),
    path("404/", TemplateView.as_view(template_name="404.html"), name="404"),
    path("500/", TemplateView.as_view(template_name="500.html"), name="500"),
]

lemarche/companies/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.utils import timezone
from django_better_admin_arrayfield.models.fields import ArrayField


class CompanyQuerySet(models.QuerySet):
    def has_user(self):
        return self.filter(users__isnull=False).distinct()

    def has_email_domain(self):
        return self.exclude(email_domain_list=[])


class Company(models.Model):
    name = models.CharField(verbose_name="Nom", max_length=255)
    slug = models.SlugField(verbose_name="Slug", max_length=255, unique=True)
    description = models.TextField(verbose_name="Description", blank=True)
    siret = models.CharField(verbose_name="Siret", max_length=14, blank=True)
    website = models.URLField(verbose_name="Site web", blank=True)
    logo_url = models.URLField(verbose_name="Lien vers le logo", max_length=500, blank=True)

    email_domain_list = ArrayField(
        verbose_name="Liste des noms de domaine d'e-mails",
        help_text="@entreprise.fr (sans le @)",
        base_field=models.CharField(max_length=255),
        blank=True,
        default=list,
    )

    created_at = models.DateTimeField(verbose_name="Date de création", default=timezone.now)
    updated_at = models.DateTimeField(verbose_name="Date de modification", auto_now=True)

    objects = models.Manager.from_queryset(CompanyQuerySet)()

    class Meta:
        verbose_name = "Entreprise"
        verbose_name_plural = "Entreprises"

    def __str__(self):
        return self.name

    def set_slug(self):
        """
        The slug field should be unique.
        """
        if not self.slug:
            self.slug = slugify(self.name)[:50]

    def save(self, *args, **kwargs):
        """Generate the slug field before saving."""
        self.set_slug()
        super().save(*args, **kwargs)

lemarche/cpv/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.template.defaultfilters import slugify
from django.utils import timezone


class CodeQuerySet(models.QuerySet):
    def has_sector(self):
        """Only return codes who have at least 1 Sector."""
        return self.prefetch_related("sectors").filter(sectors__isnull=False).distinct()


class Code(models.Model):
    name = models.CharField(verbose_name="Nom", max_length=255)
    slug = models.SlugField(verbose_name="Slug", max_length=255, unique=True)
    cpv_code = models.CharField(verbose_name="Code", max_length=8)
    hierarchy_level = models.IntegerField(
        verbose_name="Niveau hiérarchique", validators=[MinValueValidator(1), MaxValueValidator(7)]
    )

    sectors = models.ManyToManyField(
        "sectors.Sector", verbose_name="Secteurs d'activité", related_name="cpv_codes", blank=True
    )

    created_at = models.DateTimeField(verbose_name="Date de création", default=timezone.now)
    updated_at = models.DateTimeField(verbose_name="Date de modification", auto_now=True)

    objects = models.Manager.from_queryset(CodeQuerySet)()

    class Meta:
        verbose_name = "Code CPV"
        verbose_name_plural = "Code CPV"
        ordering = ["cpv_code"]

    def __str__(self):
        return f"{self.name} ({self.cpv_code})"

    def set_slug(self):
        """
        The slug field should be unique.
        """
        if not self.slug:
            self.slug = f"{str(self.cpv_code)}-{slugify(self.name)[:40]}"

    def set_hierarchy_level(self):
        """
        From 1 (XX000000) to 7 (XXXXXXXX).
        """
        if self.cpv_code:
            cpv_code_small = self.cpv_code[2:]
            self.hierarchy_level = len(cpv_code_small.rstrip("0")) + 1

    def save(self, *args, **kwargs):
        """Generate the slug field before saving."""
        self.set_slug()
        self.set_hierarchy_level()
        super().save(*args, **kwargs)

lemarche/cms/forms.py
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from wagtail.admin.forms import WagtailAdminPageForm


class ArticlePageForm(WagtailAdminPageForm):
    def clean(self):
        cleaned_data = super().clean()
        is_body_page = cleaned_data.get("body")
        is_static_page = cleaned_data.get("is_static_page") and cleaned_data.get("template_name")

        if not (is_body_page or is_static_page):
            self.add_error(
                self.error_class(error_class="nonfield"),
                """Vous devez définir un contenu pour l'article ou si c'est une page statique,
                appuyer sur la case à cocher et renseigner un nom de template valide""",
            )

        if is_static_page:
            template_name = cleaned_data.get("template_name")
            try:
                get_template(f"cms/static/{template_name}")
            except TemplateDoesNotExist:
                self.add_error(
                    "template_name",
                    """Vous devez entrer un nom de template qui existe.
                    En cas de soucis n'hésitez pas à contacter un développeur""",
                )
        return cleaned_data

lemarche/tenders/forms.py
from django import forms

from lemarche.tenders.models import Tender


class TenderAdminForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["contact_email_list"].delimiter = ";"  # Or whichever other character you want.

    class Meta:
        model = Tender
        fields = "__all__"

lemarche/users/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

from lemarche.users.models import User


class UserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("email",)


class UserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ("email",)

lemarche/www/conversations/forms.py
from django import forms

from lemarche.utils.mtcaptcha import check_captcha_token


class ContactForm(forms.Form):
    first_name = forms.CharField(
        label="Votre prénom", widget=forms.TextInput(attrs={"autofocus": "autofocus"}), required=True
    )
    last_name = forms.CharField(label="Votre nom", required=True)
    email = forms.EmailField(label="Votre email")
    subject = forms.CharField(max_length=200, label="Sujet de la demande")
    body_message = forms.CharField(label="Votre message", widget=forms.Textarea)

    def __init__(self, user=None, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        if user and user.is_authenticated:
            self.fields["first_name"].widget = forms.HiddenInput()
            self.fields["last_name"].widget = forms.HiddenInput()
            self.fields["email"].widget = forms.HiddenInput()

    def clean(self):
        super().clean()
        if not check_captcha_token(self.data):
            raise forms.ValidationError("Le code de protection est incorrect. Veuillez réessayer.")

lemarche/www/dashboard/forms.py
from django import forms

from lemarche.users.models import User


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["first_name", "last_name", "phone", "email"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Mandatory fields.
        self.fields["first_name"].required = True
        self.fields["last_name"].required = True
        self.fields["email"].required = True

        # Disabled fields
        self.fields["email"].disabled = True

lemarche/templates/frontend/common/_itou_header.html
{% load static %}

{% comment 'migration fix' %}
{% if app.environment == 'dev' %}
    <div class="alert alert-warning fixed-bottom">DEV</div>
{% endif %}
{% if app.session.get('isAdmin') %}
    <div class="alert alert-danger fixed-bottom">ADMIN MODE</div>
{% endif %}

{% endcomment %}

<!-- header of the page -->
<!-- ITOU migration -->
<header class="s-header s-header--marche sticky-top" role="banner" id="header">
  <section class="s-header__container container">
    <div class="s-header__row row">
      <div class="s-header__col s-header__col--logo col-auto d-flex align-items-center pr-0 pr-md-3">
        <a href="{% url 'pages:home' %}" class="s-header__logo-ministere"><img src="{% static 'img/logo-ministere-emploi.svg' %}" alt="Ministère de l'emploi"></a>
      </div>
      <div class="s-header__col s-header__col--logo col-auto d-flex align-items-center px-0 px-md-3">
        <a href="{% url 'pages:home' %}"/><img src="{% static 'itou/images/logo-marche-inclusion.svg' %}" alt="Le marché de l'inclusion"></a>
      </div>
      {% comment "hidden" %}
      <div class="s-header__col s-header__col--nav col d-none d-xl-inline-flex d-xl-flex align-items-center justify-content-end">
        <nav role="navigation">
          <ul>
            <!-- Missing "dashboard-dropdown" stuff -->
            {% if user.is_authenticated %}
                <li>{{ user.first_name }}</li>
                <li>
                    <a id="h_login" href="{% url 'auth:logout' %}" tabindex="7" rel="noopener">
                        <span>Déconnexion</span>
                    </a>
                </li>
            {% else %}
                <li>
                    <a id="h_login" href="{% url 'auth:login' %}" tabindex="7" rel="noopener">
                        <span>Connexion</span>
                        <span class="ml-1"><img src="{% static 'itou/images/ico-user.svg' %}" alt=""></span>
                    </a>
                </li>
                <li>
                  <a id="h_connect" href="{% url 'auth:signup' %}" tabindex="6"  class="btn btn-primary btn-ico" rel="noopener">
                    <span>Inscription</span>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16">
                        <path fill="currentColor" fill-rule="nonzero" stroke="currentColor" d="M1.964 8.95h11.03L9.51 12.737a.451.451 0 00.037.646.474.474 0 00.66-.037L14.386 8.8l.035-.043.033-.05.013-.05V8.539c0-.012.033-.02.033-.044v-.151l-.014-.05-.019-.03-.034-.045-4.193-4.566a.474.474 0 00-.66-.037.452.452 0 00-.036.646l3.45 3.777H1.963a.46.46 0 00-.464.455.46.46 0 00.464.455z"></path>
                    </svg>
                  </a>
                </li>
            {% endif %}
          </ul>
        </nav>
      </div>
      {% endcomment %}
      <div class="s-header__col s-header__col--burger col d-flex align-items-center justify-content-end d-xl-none" data-toggle="burger">
        <span id="burger"><img src="{% static 'itou/images/picto-burger.svg' %}" alt="Menu" /></span>
        <span id="close"><img src="{% static 'itou/images/picto-close.svg' %}" alt="Fermer" /></span>
      </div>
      <div id="burgerNav">
        <nav role="navigation">
          <ul>
            <li>
                <a href="#" tabindex="5" rel="noopener" id="h_fav">
                    <span>Favoris</span>
                    <span id="fav-count" class="fs-xs badge badge-marche badge-pill ml-1"></span>
                </a>                
            </li>
            {% comment 'migration fix' %}
            {%- if app.user is not null and is_granted("IS_AUTHENTICATED_FULLY") -%}
                <li id="dashboard-dropdown" class="dropdown">
                    <a id="dashboard-link" class="btn btn-outline-primary" href="{{ path('cocorico_user_dashboard_profile_edit_about_me') }}" tabindex="6" title="My Dashboard" data-toggle="dropdown" role="button" aria-expanded="false" rel="noopener">
                        <span>{{ 'nav.dashboard.link'|trans }}</span>
                        <span id="nb-unread-msg" class="fs-xs badge badge-marche badge-pill ml-1"></span>
                    </a>
                    {% include '@CocoricoCore/Frontend/Common/_itou_nav.html.twig' with {'nav_dashboard_current':'', 'dropdown_extra_class':''} only %}
                </li>
            {%- else -%}
                <li>
                    <a id="h_login" href="{{ path('cocorico_user_login') }}" tabindex="7" rel="noopener">
                        <span>{{ 'nav.login.link'|trans }}</span>
                        <span class="ml-1"><img src="/itou/images/ico-user.svg" alt=""></span>
                    </a>
                </li>
            {%- endif -%}
            {# New listing link #}
            {% if app.session.get('canPublish') %}
                <li>
                    <a id="new_offer" href="{{ path('cocorico_listing_new') }}" class="btn btn-outline-primary" tabindex="9" rel="noopener">
                        <span>{{ 'nav.listing.new.link'|trans }}</span>
                    </a>
                </li>
            {% endif %}            
            {%- if app.user is null -%}
                <li>
                    <a id="h_connect" href="{{ path('cocorico_user_register') }}" tabindex="6"  class="btn btn-primary btn-ico" rel="noopener">
                        <span>
                            {{ 'nav.register.link'|trans }}
                        </span>
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16">
                            <path fill="currentColor" fill-rule="nonzero" stroke="currentColor" d="M1.964 8.95h11.03L9.51 12.737a.451.451 0 00.037.646.474.474 0 00.66-.037L14.386 8.8l.035-.043.033-.05.013-.05V8.539c0-.012.033-.02.033-.044v-.151l-.014-.05-.019-.03-.034-.045-4.193-4.566a.474.474 0 00-.66-.037.452.452 0 00-.036.646l3.45 3.777H1.963a.46.46 0 00-.464.455.46.46 0 00.464.455z"></path>
                        </svg>
                    </a>
                </li>
            {% endif %}
            {% endcomment %}
          </ul>
        </nav>
      </div>
    </div>
  </section>
</header>